### ISSUE TITLE
Character Count

### ISSUE THREAD

**Issue by Shruti2791** [ganisivakumar/ruby_tutorial#3]
1) Write comments above the line of code.
2) Why do we need to downcase the string first and then pass it to the method. Instead this should be the task of the method itself. Isn't it ?

**Comment by ganisivakumar** [comment]
Yeah,it should be associated with method only.I changed it.
I also changed the placement of comments in the code.

**Comment by Shruti2791** [comment]
Why so many unnecessary empty lines ? Do not leave so many empty lines. However one empty line is required at the end of the line.
The exercise still stands accepted :+1:
